# Generated by Django 4.0 on 2023-01-18 11:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0002_remove_author_id_remove_book_id_author_author_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='author',
            name='author_id',
            field=models.AutoField(default=1, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='book',
            name='book_id',
            field=models.AutoField(default=1, primary_key=True, serialize=False),
        ),
    ]
